"""Prompt templates for analysis (P2-01, P2-02, P2-03)."""

# ruff: noqa: E501
# Prompt templates contain long lines by design

SINGLE_ANALYSIS_SYSTEM_PROMPT = """You are an expert analyst of 3GPP standardization documents.
Your task is to analyze a single contribution document and extract key information.

Guidelines:
1. Analyze the document thoroughly based on the provided content sections
2. Identify the main purpose and proposals in the document
3. Extract specific changes being proposed (additions, modifications, deletions)
4. Identify potential issues, concerns, or discussion points
5. Always reference specific clause/section numbers when available
6. Be concise but comprehensive
7. Focus on technical content, not administrative details

Output Format:
- summary: A concise overview (2-4 sentences) of what the document proposes
- changes: List of changes proposed, with type and clause reference
- issues: List of concerns or discussion points, with severity (high/medium/low)
"""

SINGLE_ANALYSIS_USER_PROMPT = """Analyze the following 3GPP contribution document.

## Document Information
- Contribution Number: {contribution_number}
- Title: {title}
- Meeting: {meeting}
- Source: {source}

## Document Content (organized by sections)

{evidence_content}

---

Please provide a structured analysis with:
1. A summary of the document's main purpose and proposals
2. List of proposed changes (type: addition/modification/deletion, description, clause)
3. List of issues or discussion points (description and severity: high/medium/low)

Ensure each finding references the relevant section/clause when possible.
"""

COMPARE_ANALYSIS_SYSTEM_PROMPT = """You are an expert analyst of 3GPP standardization documents.
Your task is to compare two contribution documents and identify similarities and differences.

Guidelines:
1. Identify common themes and proposals between the documents
2. Highlight key differences in approach, scope, or recommendations
3. Consider technical implications of the differences
4. Provide a recommendation on how to reconcile or prioritize the proposals
5. Reference specific clauses/sections when discussing differences

Output Format:
- common_points: List of similarities between the documents
- differences: List of differences, each with aspect, doc1_position, and doc2_position
- recommendation: Overall recommendation for handling the two proposals
"""

COMPARE_ANALYSIS_USER_PROMPT = """Compare the following two 3GPP contribution documents.

## Document 1
- Contribution Number: {doc1_contribution_number}
- Title: {doc1_title}
- Meeting: {doc1_meeting}

### Content
{doc1_content}

---

## Document 2
- Contribution Number: {doc2_contribution_number}
- Title: {doc2_title}
- Meeting: {doc2_meeting}

### Content
{doc2_content}

---

Please provide a comparison analysis with:
1. Common points between the two documents
2. Key differences (aspect, position of each document)
3. Recommendation for handling these proposals
"""

# Review sheet template for Markdown generation
REVIEW_SHEET_TEMPLATE = """# Review Sheet: {contribution_number}

## Document Information

| Field | Value |
|-------|-------|
| Contribution | {contribution_number} |
| Meeting | {meeting} |
| Title | {title} |
| Source | {source} |
| Analysis Date | {analysis_date} |

---

## Summary

{summary}

---

## Proposed Changes

{changes_section}

---

## Key Issues and Discussion Points

{issues_section}

---

## Evidence References

{evidences_section}

---

*Generated by 3GPP Analyzer v{strategy_version}*
"""

# Section templates for review sheet
CHANGE_ITEM_TEMPLATE = """### {index}. {change_type}: {description}
- **Clause**: {clause}
"""

ISSUE_ITEM_TEMPLATE = """### {index}. [{severity}] {description}
"""

EVIDENCE_ITEM_TEMPLATE = (
    '- **{contribution_number}** (Clause {clause}, Page {page}): "{content_preview}..."'
)
