"""Prompt templates for analysis (P2-01, P2-02, P2-03)."""

# ruff: noqa: E501
# Prompt templates contain long lines by design

# Language-specific instructions for analysis output
LANGUAGE_INSTRUCTIONS = {
    "ja": """
Output Language: Japanese (日本語)
- Write the summary, change descriptions, and issue descriptions in Japanese
- Technical terms (3GPP terminology, clause numbers, specification references) should remain in English
- Evidence citations remain in the original document language (do not translate)
""",
    "en": """
Output Language: English
- Write the summary, change descriptions, and issue descriptions in English
- All technical terms should be in English
- Evidence citations remain in the original document language (do not translate)
""",
}


def get_single_analysis_system_prompt(language: str = "ja") -> str:
    """Get single analysis system prompt with language instruction."""
    language_instruction = LANGUAGE_INSTRUCTIONS.get(language, LANGUAGE_INSTRUCTIONS["ja"])
    return f"""You are an expert analyst of 3GPP standardization documents.
Your task is to analyze a single contribution document and extract key information.

Guidelines:
1. Analyze the document thoroughly based on the provided content sections
2. Identify the main purpose and proposals in the document
3. Extract specific changes being proposed (additions, modifications, deletions)
4. Identify potential issues, concerns, or discussion points
5. Always reference specific clause/section numbers when available
6. Be concise but comprehensive
7. Focus on technical content, not administrative details
{language_instruction}
Output Format:
- summary: A concise overview (2-4 sentences) of what the document proposes
- changes: List of changes proposed, with type and clause reference
- issues: List of concerns or discussion points, with severity (high/medium/low)
"""


# Legacy constant for backwards compatibility (uses Japanese by default)
SINGLE_ANALYSIS_SYSTEM_PROMPT = """You are an expert analyst of 3GPP standardization documents.
Your task is to analyze a single contribution document and extract key information.

Guidelines:
1. Analyze the document thoroughly based on the provided content sections
2. Identify the main purpose and proposals in the document
3. Extract specific changes being proposed (additions, modifications, deletions)
4. Identify potential issues, concerns, or discussion points
5. Always reference specific clause/section numbers when available
6. Be concise but comprehensive
7. Focus on technical content, not administrative details

Output Format:
- summary: A concise overview (2-4 sentences) of what the document proposes
- changes: List of changes proposed, with type and clause reference
- issues: List of concerns or discussion points, with severity (high/medium/low)
"""

SINGLE_ANALYSIS_USER_PROMPT = """Analyze the following 3GPP contribution document.

## Document Information
- Contribution Number: {contribution_number}
- Title: {title}
- Meeting: {meeting}
- Source: {source}

## Document Content (organized by sections)

{evidence_content}

---

Please provide a structured analysis with:
1. A summary of the document's main purpose and proposals
2. List of proposed changes (type: addition/modification/deletion, description, clause)
3. List of issues or discussion points (description and severity: high/medium/low)

Ensure each finding references the relevant section/clause when possible.
"""

# Review sheet template for Markdown generation
REVIEW_SHEET_TEMPLATE = """# Review Sheet: {contribution_number}

## Document Information

| Field | Value |
|-------|-------|
| Contribution | {contribution_number} |
| Meeting | {meeting} |
| Title | {title} |
| Source | {source} |
| Analysis Date | {analysis_date} |

---

## Summary

{summary}

---

## Proposed Changes

{changes_section}

---

## Key Issues and Discussion Points

{issues_section}

---

## Evidence References

{evidences_section}

---

*Generated by 3GPP Analyzer v{strategy_version}*
"""

# Section templates for review sheet
CHANGE_ITEM_TEMPLATE = """### {index}. {change_type}: {description}
- **Clause**: {clause}
"""

ISSUE_ITEM_TEMPLATE = """### {index}. [{severity}] {description}
"""

EVIDENCE_ITEM_TEMPLATE = (
    '- **{contribution_number}** (Clause {clause}, Page {page}): "{content_preview}..."'
)


# Custom analysis prompts
def get_custom_analysis_system_prompt(language: str = "ja") -> str:
    """Get custom analysis system prompt with language instruction."""
    language_instruction = LANGUAGE_INSTRUCTIONS.get(language, LANGUAGE_INSTRUCTIONS["ja"])
    return f"""You are an expert analyst of 3GPP standardization documents.
Your task is to analyze a document based on the user's specific question or perspective.

Guidelines:
1. Focus on answering the user's specific question or analyzing from their requested perspective
2. Reference specific clause/section numbers when providing evidence
3. Be thorough but focused on what the user asked
4. Include relevant evidence from the document to support your answer
5. If the question cannot be answered from the document content, explain what information is missing
{language_instruction}
Provide a comprehensive answer that directly addresses the user's question.
"""


CUSTOM_ANALYSIS_USER_PROMPT = """Analyze the following 3GPP contribution document based on the user's question.

## Document Information
- Contribution Number: {contribution_number}
- Title: {title}
- Meeting: {meeting}
- Source: {source}

## User's Question/Perspective
{custom_prompt}

## Document Content (organized by sections)

{evidence_content}

---

Please provide a comprehensive answer to the user's question, citing relevant sections from the document.
"""
